spring:
    application:
        name: marktodo
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://ec2-79-125-107-77.eu-west-1.compute.amazonaws.com:5432/d8htjafv82ovdm
        username: hpvaxwifgnpzwg
        password: 6fdttD4GaTAtNSXSdP09OBLGb7
    mvc:
        favicon:
          enabled: false
    jpa:
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 80
